<?php

declare(strict_types=1);

$site = [
    'name' => 'HavenBuild',
    'tagline' => 'Homes built, sealed, styled, and powered',
    'city' => 'Kerala',
    'phone_display' => '+91 90000 00000',
    'phone_tel' => '+919000000000',
    'whatsapp' => '919000000000',
    'service_area' => 'Home services in Kollam, Trivandrum, and across Kerala',
    'seo_title' => 'Home Construction in Kollam, Waterproofing in Trivandrum | HavenBuild',
    'seo_description' => 'Construction mainly in Kollam, then Trivandrum. Waterproofing mainly in Trivandrum, then Kollam. Painting in Kollam and Trivandrum. Interior design and solar panel installation across Kerala.',
    'seo_keywords' => 'home construction Kollam, house builders Trivandrum, waterproofing Trivandrum, terrace waterproofing Kollam, interior design Kerala, house painting Kollam, house painting Trivandrum, solar panel installation Kerala, home services Kerala',
    'geo_region' => 'IN-KL',
    'geo_placename' => 'Kerala',
];

$db = [
    'host' => '127.0.0.1',
    'name' => 'havenbuild',
    'user' => 'root',
    'pass' => '',
    'charset' => 'utf8mb4',
];

$services = [
    [
        'slug' => 'home-construction',
        'name' => 'Home construction',
        'menu' => 'Construction',
        'image' => 'images/construction.jpg',
        'alt' => 'A Kerala concrete house under construction, with columns, a flat slab, and coconut palms',
        'gallery' => [
            ['src' => 'images/hero-home.jpg', 'alt' => 'A finished Kerala concrete house with a flat roof and a porch'],
        ],
        'tint' => 'clay',
        'icon' => 'home',
        'promise' => 'New homes, extensions, and renovations shaped around how you live.',
        'coverage' => 'Mainly Kollam, then Trivandrum',
        'coverage_note' => 'Most construction work is in Kollam. We also build and renovate houses in Trivandrum.',
        'summary' => 'From an extra room to a full house, the structure, finishes, and sequence of work are agreed before anyone starts.',
        'included' => [
            'A layout conversation before drawings are locked',
            'Civil work from foundation or slab through finishes',
            'One written quote that lists what is included',
        ],
        'jobs' => ['Independent houses', 'Floor and room extensions', 'Kitchen and full-home renovations'],
        'seo_title' => 'Home Construction in Kollam and Trivandrum | HavenBuild',
        'seo_description' => 'New homes, extensions, and renovations, mainly in Kollam, with construction also in Trivandrum.',
        'seo_keywords' => 'home construction Kollam, house construction Kollam, builders in Kollam, home renovation Kollam, house construction Trivandrum, construction company Trivandrum',
        'geo_placename' => 'Kollam',
        'geo_position' => '8.8932;76.6141',
    ],
    [
        'slug' => 'waterproofing',
        'name' => 'Waterproofing',
        'menu' => 'Waterproofing',
        'image' => 'images/waterproofing.jpg',
        'alt' => 'Workers coating the flat concrete terrace of a Kerala house',
        'gallery' => [
            ['src' => 'images/waterproofing-bath.jpg', 'alt' => 'A concrete bathroom floor being sealed before tiling'],
        ],
        'tint' => 'teal',
        'icon' => 'drop',
        'promise' => 'Terrace, bathroom, basement, and wall damp treated at the source.',
        'coverage' => 'Mainly Trivandrum, then Kollam',
        'coverage_note' => 'Most waterproofing is in Trivandrum. We also treat terraces, bathrooms, and damp walls in Kollam.',
        'summary' => 'Leaks are traced before coating goes on, so the repair matches the way water is actually getting in.',
        'included' => [
            'Inspection of the leak path',
            'Surface preparation before any coating',
            'A note of every area that was treated',
        ],
        'jobs' => ['Terrace and roof slabs', 'Bathrooms and wet areas', 'Basements and damp walls'],
        'seo_title' => 'Waterproofing in Trivandrum and Kollam | HavenBuild',
        'seo_description' => 'Terrace, bathroom, and wall waterproofing, mainly in Trivandrum, with work also in Kollam.',
        'seo_keywords' => 'waterproofing Trivandrum, terrace waterproofing Trivandrum, bathroom waterproofing Trivandrum, waterproofing Kollam, damp proofing Kollam',
        'geo_placename' => 'Trivandrum',
        'geo_position' => '8.5241;76.9366',
    ],
    [
        'slug' => 'interior-design',
        'name' => 'Interior design',
        'menu' => 'Interiors',
        'image' => 'images/interior.jpg',
        'alt' => 'A living room in a Kerala concrete house, with a flat ceiling and coconut palms outside',
        'gallery' => [
            ['src' => 'images/interior-kitchen.jpg', 'alt' => 'A kitchen in a Kerala concrete house, with a granite counter and a concrete ceiling'],
        ],
        'tint' => 'sage',
        'icon' => 'layout',
        'promise' => 'Layouts, materials, and finishes you can approve before work begins.',
        'coverage' => 'All across Kerala',
        'coverage_note' => 'Interior design is available for homes across Kerala.',
        'summary' => 'Rooms are planned for daily use first: storage, light, and movement, then the materials that suit them.',
        'included' => [
            'A layout based on how the room is used',
            'Material and finish suggestions',
            'A finish schedule you can sign off',
        ],
        'jobs' => ['Living and bedroom layouts', 'Kitchen and wardrobe planning', 'Material and colour selection'],
        'seo_title' => 'Interior Design across Kerala | HavenBuild',
        'seo_description' => 'Home interior design for living rooms, kitchens, and wardrobes across Kerala.',
        'seo_keywords' => 'interior design Kerala, interior designers Kerala, home interiors Kollam, home interiors Trivandrum, kitchen design Kerala',
        'geo_placename' => 'Kerala',
    ],
    [
        'slug' => 'painting',
        'name' => 'Painting',
        'menu' => 'Painting',
        'image' => 'images/painting.jpg',
        'alt' => 'A painter coating a wall inside a Kerala concrete house',
        'gallery' => [
            ['src' => 'images/painting-exterior.jpg', 'alt' => 'The cream wall of a flat-roof Kerala concrete house being painted'],
        ],
        'tint' => 'sand',
        'icon' => 'brush',
        'promise' => 'Interior and exterior painting with proper prep, not just a fresh coat.',
        'coverage' => 'Kollam and Trivandrum',
        'coverage_note' => 'Painting is available for homes in Kollam and Trivandrum.',
        'summary' => 'Surfaces are cleaned, filled, and primed so the finish stays even on walls that have already lived a little.',
        'included' => [
            'Surface prep, primer, and finish coats',
            'Floors and furniture covered before work',
            'Interior walls, ceilings, and exterior faces',
        ],
        'jobs' => ['Full interior repaints', 'Exterior weather coats', 'Wood and metal touch-ups'],
        'seo_title' => 'House Painting in Kollam and Trivandrum | HavenBuild',
        'seo_description' => 'Interior and exterior house painting for homes in Kollam and Trivandrum.',
        'seo_keywords' => 'house painting Kollam, painting contractors Kollam, house painting Trivandrum, interior painting Trivandrum, exterior painting Kerala',
        'geo_placename' => 'Kollam, Trivandrum',
    ],
    [
        'slug' => 'solar',
        'name' => 'Solar panel installation',
        'menu' => 'Solar',
        'image' => 'images/solar.jpg',
        'alt' => 'Solar panels on the flat concrete terrace of a Kerala house',
        'gallery' => [
            ['src' => 'images/solar-install.jpg', 'alt' => 'A technician fitting solar cables on a concrete terrace'],
        ],
        'tint' => 'gold',
        'icon' => 'sun',
        'promise' => 'Rooftop residential systems sized to the roof and the bill.',
        'coverage' => 'All across Kerala',
        'coverage_note' => 'Rooftop solar is available for homes across Kerala.',
        'summary' => 'The roof is checked first. Panel count follows how much power the house uses, not a packaged guess.',
        'included' => [
            'Roof assessment and panel layout',
            'System size based on household use',
            'Installation and a walkthrough of the setup',
        ],
        'jobs' => ['Rooftop home systems', 'Inverter and wiring to the board', 'Small expansions of an existing array'],
        'seo_title' => 'Solar Panel Installation across Kerala | HavenBuild',
        'seo_description' => 'Rooftop solar panel installation for homes across Kerala.',
        'seo_keywords' => 'solar panel installation Kerala, rooftop solar Kerala, solar installation Kollam, solar panels Trivandrum, home solar Kerala',
        'geo_placename' => 'Kerala',
    ],
];
