<?php

declare(strict_types=1);

$site = [
    'name' => 'HavenBuild',
    'tagline' => 'Homes built, sealed, styled, and powered',
    'city' => 'Kerala',
    'phone_display' => '+91 90000 00000',
    'phone_tel' => '+919000000000',
    'whatsapp' => '919000000000',
    'service_area' => 'Home services in Kollam, Trivandrum, and across Kerala',
    'seo_title' => 'Home Construction in Kollam, Waterproofing in Trivandrum | HavenBuild',
    'seo_description' => 'Construction mainly in Kollam, then Trivandrum. Waterproofing mainly in Trivandrum, then Kollam. Painting in Kollam and Trivandrum. Interior design and solar panel installation across Kerala.',
    'seo_keywords' => 'home construction Kollam, house builders Trivandrum, waterproofing Trivandrum, terrace waterproofing Kollam, interior design Kerala, house painting Kollam, house painting Trivandrum, solar panel installation Kerala, home services Kerala',
    'geo_region' => 'IN-KL',
    'geo_placename' => 'Kerala',
];

$db = [
    'host' => '127.0.0.1',
    'name' => 'havenbuild',
    'user' => 'root',
    'pass' => '',
    'charset' => 'utf8mb4',
];

$services = [
    [
        'slug' => 'home-construction',
        'name' => 'Home construction',
        'menu' => 'Construction',
        'image' => 'images/construction.jpg',
        'alt' => 'A Kerala concrete house under construction, with columns, a flat slab, and coconut palms',
        'gallery' => [
            ['src' => 'images/hero-home.jpg', 'alt' => 'A finished Kerala concrete house with a flat roof and a porch'],
            ['src' => 'images/construction-slab.jpg', 'alt' => 'Workers levelling a freshly cast concrete roof slab'],
            ['src' => 'images/construction-blockwork.jpg', 'alt' => 'Concrete-block walls rising between RCC columns'],
        ],
        'tint' => 'clay',
        'icon' => 'home',
        'promise' => 'New homes, extensions, and renovations shaped around how you live.',
        'coverage' => 'Mainly Kollam, then Trivandrum',
        'coverage_note' => 'Most construction work is in Kollam. We also build and renovate houses in Trivandrum.',
        'summary' => 'From an extra room to a full house, the structure, finishes, and sequence of work are agreed before anyone starts.',
        'story_title' => 'From the ground to the last finish.',
        'story' => [
            'A new house, an extra floor, or a renovation starts with how the family uses the rooms. The plan, the structure, and the finishes are agreed in writing before the site is opened.',
            'On a concrete house that means the foundation or the existing slab, the columns and beams, the blockwork, and then the floors, doors, and fittings. Each stage is checked before the next one begins.',
        ],
        'steps' => [
            ['title' => 'Site and layout', 'text' => 'We walk the plot or the existing house and note levels, access, and what has to stay. The room layout is settled before concrete is ordered.'],
            ['title' => 'Structure', 'text' => 'Foundation, columns, beams, and slabs are cast in sequence. Steel and concrete are checked before they are covered up.'],
            ['title' => 'Walls and openings', 'text' => 'Blockwork, lintels, door and window openings, and the staircase are built to the agreed plan, not adjusted once the walls are up.'],
            ['title' => 'Finishes', 'text' => 'Flooring, plaster, and fittings follow a list you have already seen, so the house is not redesigned while the work is underway.'],
        ],
        'included' => [
            'A layout conversation before drawings are locked',
            'Civil work from foundation or slab through plaster and flooring',
            'One written quote that lists every stage that is included',
        ],
        'jobs' => ['Independent concrete houses', 'Floor and room extensions', 'Kitchen and full-home renovations'],
        'seo_title' => 'Home Construction in Kollam and Trivandrum | HavenBuild',
        'seo_description' => 'New homes, extensions, and renovations, mainly in Kollam, with construction also in Trivandrum.',
        'seo_keywords' => 'home construction Kollam, house construction Kollam, builders in Kollam, home renovation Kollam, house construction Trivandrum, construction company Trivandrum',
        'geo_placename' => 'Kollam',
        'geo_position' => '8.8932;76.6141',
    ],
    [
        'slug' => 'waterproofing',
        'name' => 'Waterproofing',
        'menu' => 'Waterproofing',
        'image' => 'images/waterproofing.jpg',
        'alt' => 'Workers coating the flat concrete terrace of a Kerala house',
        'gallery' => [
            ['src' => 'images/waterproofing-bath.jpg', 'alt' => 'A concrete bathroom floor being sealed before tiling'],
            ['src' => 'images/waterproofing-parapet.jpg', 'alt' => 'Waterproof coating brushed along a concrete parapet joint'],
            ['src' => 'images/waterproofing-wall.jpg', 'alt' => 'A damp concrete wall being treated inside a room'],
        ],
        'tint' => 'teal',
        'icon' => 'drop',
        'promise' => 'Terrace, bathroom, basement, and wall damp treated at the source.',
        'coverage' => 'Mainly Trivandrum, then Kollam',
        'coverage_note' => 'Most waterproofing is in Trivandrum. We also treat terraces, bathrooms, and damp walls in Kollam.',
        'summary' => 'Leaks are traced before coating goes on, so the repair matches the way water is actually getting in.',
        'story_title' => 'Stop the water where it gets in.',
        'story' => [
            'A terrace leak, a damp bedroom wall, or a bathroom that stains the ceiling below is traced before any coating goes on. The repair follows the path of the water, not a standard package.',
            'On a concrete house the usual weak points are the terrace slab, the parapet joint, the sunshade, and the wet areas. Those are opened, prepared, and sealed, then written down so you know exactly what was treated.',
        ],
        'steps' => [
            ['title' => 'Find the path', 'text' => 'We look at stains, slopes, outlets, and the rooms below before choosing a treatment. Coating a dry-looking patch is not the job.'],
            ['title' => 'Open and prepare', 'text' => 'Loose plaster, failed coating, and blocked outlets are removed so the new layer can bond to sound concrete.'],
            ['title' => 'Seal the slab and joints', 'text' => 'The terrace, the parapet joint, and the pipe penetrations are coated and detailed, including the turn-up at the wall.'],
            ['title' => 'Wet areas', 'text' => 'Bathrooms and balconies are waterproofed before tiling, with the coating carried up the walls so water cannot creep behind the tile.'],
        ],
        'included' => [
            'Inspection of the leak path before any product is chosen',
            'Surface preparation, then coating of every area that was opened',
            'A written note of the terrace, joints, and rooms that were treated',
        ],
        'jobs' => ['Terrace and roof slabs', 'Bathrooms and wet areas', 'Basements and damp walls'],
        'seo_title' => 'Waterproofing in Trivandrum and Kollam | HavenBuild',
        'seo_description' => 'Terrace, bathroom, and wall waterproofing, mainly in Trivandrum, with work also in Kollam.',
        'seo_keywords' => 'waterproofing Trivandrum, terrace waterproofing Trivandrum, bathroom waterproofing Trivandrum, waterproofing Kollam, damp proofing Kollam',
        'geo_placename' => 'Trivandrum',
        'geo_position' => '8.5241;76.9366',
    ],
    [
        'slug' => 'interior-design',
        'name' => 'Interior design',
        'menu' => 'Interiors',
        'image' => 'images/interior.jpg',
        'alt' => 'A living room in a Kerala concrete house, with a flat ceiling and coconut palms outside',
        'gallery' => [
            ['src' => 'images/interior-kitchen.jpg', 'alt' => 'A kitchen in a Kerala concrete house, with a granite counter and a concrete ceiling'],
            ['src' => 'images/interior-bedroom.jpg', 'alt' => 'A bedroom in a Kerala concrete house looking out to coconut palms'],
            ['src' => 'images/interior-wardrobe.jpg', 'alt' => 'A built-in wardrobe in a Kerala concrete house'],
        ],
        'tint' => 'sage',
        'icon' => 'layout',
        'promise' => 'Layouts, materials, and finishes you can approve before work begins.',
        'coverage' => 'All across Kerala',
        'coverage_note' => 'Interior design is available for homes across Kerala.',
        'summary' => 'Rooms are planned for daily use first: storage, light, and movement, then the materials that suit them.',
        'story_title' => 'Rooms planned for how you actually live.',
        'story' => [
            'A concrete house gives you a shell. The interior work decides how that shell is used: where you sit, where things are stored, and how light moves through the day.',
            'Living rooms, bedrooms, kitchens, and wardrobes are planned together so the materials, colours, and storage agree with each other. You approve the layout and the finishes before carpentry starts.',
        ],
        'steps' => [
            ['title' => 'How the room is used', 'text' => 'We start with storage, movement, and light. A finish is chosen only after the room has a job.'],
            ['title' => 'Layout', 'text' => 'Furniture, wardrobes, and the kitchen are drawn so doors, windows, and plug points still work once the pieces are in.'],
            ['title' => 'Materials', 'text' => 'Floors, cabinets, stone, and colour are chosen as one set. You see samples before anything is ordered.'],
            ['title' => 'Making it', 'text' => 'Carpentry and finishes follow the signed schedule, room by room, instead of being decided on the day of installation.'],
        ],
        'included' => [
            'A layout based on how each room is used',
            'Material, colour, and storage suggestions you can approve',
            'A finish schedule signed before carpentry begins',
        ],
        'jobs' => ['Living and bedroom layouts', 'Kitchen and wardrobe planning', 'Material and colour selection'],
        'seo_title' => 'Interior Design across Kerala | HavenBuild',
        'seo_description' => 'Home interior design for living rooms, kitchens, and wardrobes across Kerala.',
        'seo_keywords' => 'interior design Kerala, interior designers Kerala, home interiors Kollam, home interiors Trivandrum, kitchen design Kerala',
        'geo_placename' => 'Kerala',
    ],
    [
        'slug' => 'painting',
        'name' => 'Painting',
        'menu' => 'Painting',
        'image' => 'images/painting.jpg',
        'alt' => 'A painter coating a wall inside a Kerala concrete house',
        'gallery' => [
            ['src' => 'images/painting-exterior.jpg', 'alt' => 'The cream wall of a flat-roof Kerala concrete house being painted'],
            ['src' => 'images/painting-prep.jpg', 'alt' => 'Cracks in a concrete wall being filled before painting'],
            ['src' => 'images/painting-ceiling.jpg', 'alt' => 'A painter coating the concrete ceiling of a room'],
        ],
        'tint' => 'sand',
        'icon' => 'brush',
        'promise' => 'Interior and exterior painting with proper prep, not just a fresh coat.',
        'coverage' => 'Kollam and Trivandrum',
        'coverage_note' => 'Painting is available for homes in Kollam and Trivandrum.',
        'summary' => 'Surfaces are cleaned, filled, and primed so the finish stays even on walls that have already lived a little.',
        'story_title' => 'A coat that lasts because the wall was prepared.',
        'story' => [
            'Paint fails when the surface underneath was left damp, dusty, or cracked. We clean, fill, and prime before the finish colour goes on.',
            'Interior walls, ceilings, and the outside of a concrete house are treated differently. Exteriors need a weather coat. Interiors need an even film on plaster that has already lived a little. Wood and metal are prepared on their own.',
        ],
        'steps' => [
            ['title' => 'Cover and clean', 'text' => 'Floors, fittings, and furniture are protected. Walls are washed and loose paint is scraped back to a sound surface.'],
            ['title' => 'Fill and prime', 'text' => 'Cracks and nail holes are filled. A primer seals the plaster so the finish colour stays even.'],
            ['title' => 'Finish coats', 'text' => 'Colour is applied in even coats, including corners, ceilings, and the edges around doors and windows.'],
            ['title' => 'Outside faces', 'text' => 'Exterior plaster is checked for damp, then given a weather coat that can take sun and rain.'],
        ],
        'included' => [
            'Surface preparation, primer, and finish coats',
            'Floors, fittings, and furniture covered before work starts',
            'Interior walls and ceilings, plus the exterior faces of the house',
        ],
        'jobs' => ['Full interior repaints', 'Exterior weather coats', 'Wood and metal touch-ups'],
        'seo_title' => 'House Painting in Kollam and Trivandrum | HavenBuild',
        'seo_description' => 'Interior and exterior house painting for homes in Kollam and Trivandrum.',
        'seo_keywords' => 'house painting Kollam, painting contractors Kollam, house painting Trivandrum, interior painting Trivandrum, exterior painting Kerala',
        'geo_placename' => 'Kollam, Trivandrum',
    ],
    [
        'slug' => 'solar',
        'name' => 'Solar panel installation',
        'menu' => 'Solar',
        'image' => 'images/solar.jpg',
        'alt' => 'Solar panels on the flat concrete terrace of a Kerala house',
        'gallery' => [
            ['src' => 'images/solar-install.jpg', 'alt' => 'A technician fitting solar cables on a concrete terrace'],
            ['src' => 'images/solar-terrace.jpg', 'alt' => 'A row of solar panels on a flat concrete terrace'],
            ['src' => 'images/solar-inverter.jpg', 'alt' => 'A solar inverter mounted on the wall of a concrete house'],
        ],
        'tint' => 'gold',
        'icon' => 'sun',
        'promise' => 'Rooftop residential systems sized to the roof and the bill.',
        'coverage' => 'All across Kerala',
        'coverage_note' => 'Rooftop solar is available for homes across Kerala.',
        'summary' => 'The roof is checked first. Panel count follows how much power the house uses, not a packaged guess.',
        'story_title' => 'Panels sized to the roof and the bill.',
        'story' => [
            'A concrete terrace is a good place for solar once the slab, the parapet, and the shade from neighbouring palms are checked. The system follows how much power the house uses.',
            'We set out the panels, the inverter, and the run to the distribution board, then walk you through what was installed. A small addition to an existing array is planned the same way.',
        ],
        'steps' => [
            ['title' => 'Roof and shade', 'text' => 'The terrace is measured. Shade from palms, water tanks, and nearby buildings is noted before any frame is fixed.'],
            ['title' => 'Size the system', 'text' => 'Panel count follows the monthly bill and the usable roof, not a fixed package sold in advance.'],
            ['title' => 'Mount and wire', 'text' => 'Frames are fixed to the terrace, panels are mounted, and cables run to the inverter and the distribution board.'],
            ['title' => 'Handover', 'text' => 'You see the layout, the inverter, and how to read the system before we leave the terrace.'],
        ],
        'included' => [
            'Roof assessment, shade check, and a panel layout',
            'System size based on household use and the usable terrace',
            'Installation, wiring to the board, and a walkthrough',
        ],
        'jobs' => ['Rooftop home systems', 'Inverter and wiring to the board', 'Small expansions of an existing array'],
        'seo_title' => 'Solar Panel Installation across Kerala | HavenBuild',
        'seo_description' => 'Rooftop solar panel installation for homes across Kerala.',
        'seo_keywords' => 'solar panel installation Kerala, rooftop solar Kerala, solar installation Kollam, solar panels Trivandrum, home solar Kerala',
        'geo_placename' => 'Kerala',
    ],
];
