<?php

declare(strict_types=1);

$site = [
    'name' => 'HavenBuild',
    'tagline' => 'Homes built, sealed, styled, and powered',
    'city' => 'Kerala',
    'phone_display' => '+91 90000 00000',
    'phone_tel' => '+919000000000',
    'whatsapp' => '919000000000',
    'service_area' => 'Home services in Kollam, Trivandrum, and across Kerala',
    'seo_title' => 'Home Construction in Kollam, Waterproofing in Trivandrum | HavenBuild',
    'seo_description' => 'Home construction in Kollam and Trivandrum. Waterproofing in Trivandrum and Kollam. Painting in Kollam and Trivandrum. Interior design and solar panel installation across Kerala.',
    'seo_keywords' => 'home construction Kollam, house builders Trivandrum, waterproofing Trivandrum, terrace waterproofing Kollam, interior design Kerala, house painting Kollam, house painting Trivandrum, solar panel installation Kerala, home services Kerala',
    'geo_region' => 'IN-KL',
    'geo_placename' => 'Kerala',
];

$db = [
    'host' => '127.0.0.1',
    'name' => 'havenbuild',
    'user' => 'root',
    'pass' => '',
    'charset' => 'utf8mb4',
];

$services = [
    [
        'slug' => 'home-construction',
        'name' => 'Home construction',
        'menu' => 'Construction',
        'image' => 'images/construction.jpg',
        'alt' => 'A Kerala concrete house under construction, with columns, a flat slab, and coconut palms',
        'gallery' => [
            ['src' => 'images/hero-home.jpg', 'alt' => 'A finished Kerala concrete house with a flat roof and a porch'],
            ['src' => 'images/construction-slab.jpg', 'alt' => 'Workers levelling a freshly cast concrete roof slab'],
            ['src' => 'images/construction-blockwork.jpg', 'alt' => 'Concrete-block walls rising between RCC columns'],
        ],
        'tint' => 'clay',
        'icon' => 'home',
        'promise' => 'New homes, extensions, and renovations shaped around how you live.',
        'coverage' => 'Kollam and Trivandrum',
        'coverage_note' => 'Most construction work is in Kollam. We also build and renovate houses in Trivandrum.',
        'summary' => 'We stay with the house from the plan to the keys: layout, structure, blockwork, plaster, and flooring.',
        'story_title' => 'From the plan to the keys.',
        'story' => [
            'We stay with the house from the plan to the keys: layout, structure, blockwork, plaster, and flooring. The sequence is agreed before the site opens, so the work is not redesigned halfway through.',
            'On a concrete house that means the foundation or the existing slab, the columns and beams, the blockwork, and then the floors, doors, and fittings. Each stage is checked before the next one begins.',
        ],
        'steps' => [
            ['title' => 'Site and layout', 'text' => 'We walk the plot or the existing house and note levels, access, and what has to stay. The room layout is settled before concrete is ordered.'],
            ['title' => 'Structure', 'text' => 'Foundation, columns, beams, and slabs are cast in sequence. Steel and concrete are checked before they are covered up.'],
            ['title' => 'Walls and openings', 'text' => 'Blockwork, lintels, door and window openings, and the staircase are built to the agreed plan, not adjusted once the walls are up.'],
            ['title' => 'Finishes', 'text' => 'Flooring, plaster, and fittings follow a list you have already seen, so the house is not redesigned while the work is underway.'],
        ],
        'included' => [
            'A layout conversation before drawings are locked',
            'Civil work from foundation or slab through plaster and flooring',
            'One written quote that lists every stage that is included',
        ],
        'jobs' => ['Independent concrete houses', 'Floor and room extensions', 'Kitchen and full-home renovations'],
        'seo_title' => 'Home Construction in Kollam and Trivandrum | HavenBuild',
        'seo_description' => 'New homes, extensions, and renovations in Kollam and Trivandrum.',
        'seo_keywords' => 'home construction Kollam, house construction Kollam, builders in Kollam, home renovation Kollam, house construction Trivandrum, construction company Trivandrum',
        'geo_placename' => 'Kollam',
        'geo_position' => '8.8932;76.6141',
    ],
    [
        'slug' => 'waterproofing',
        'name' => 'Waterproofing',
        'menu' => 'Waterproofing',
        'image' => 'images/waterproofing.jpg',
        'alt' => 'Workers coating the flat concrete terrace of a Kerala house',
        'gallery' => [
            ['src' => 'images/waterproofing-bath.jpg', 'alt' => 'A concrete bathroom floor being sealed before tiling'],
            ['src' => 'images/waterproofing-parapet.jpg', 'alt' => 'Waterproof coating brushed along a concrete parapet joint'],
            ['src' => 'images/waterproofing-wall.jpg', 'alt' => 'A damp concrete wall being treated inside a room'],
        ],
        'tint' => 'teal',
        'icon' => 'drop',
        'promise' => 'Terrace, bathroom, basement, and wall damp treated at the source.',
        'coverage' => 'Trivandrum and Kollam',
        'coverage_note' => 'Most waterproofing is in Trivandrum. We also treat terraces, bathrooms, and damp walls in Kollam.',
        'summary' => 'The leak is traced first. Then the terrace, parapet, sunshade, or bathroom is opened, prepared, and sealed.',
        'story_title' => 'The leak is traced first.',
        'story' => [
            'The leak is traced first. On a concrete house that is usually the terrace slab, the parapet joint, a sunshade, or a bathroom. Those areas are opened, prepared, and sealed, and you get a note of every place that was treated.',
            'The repair follows the path of the water, not a standard package. You know exactly what was treated before we leave.',
        ],
        'steps' => [
            ['title' => 'Find the path', 'text' => 'We look at stains, slopes, outlets, and the rooms below before choosing a treatment. Coating a dry-looking patch is not the job.'],
            ['title' => 'Open and prepare', 'text' => 'Loose plaster, failed coating, and blocked outlets are removed so the new layer can bond to sound concrete.'],
            ['title' => 'Seal the slab and joints', 'text' => 'The terrace, the parapet joint, and the pipe penetrations are coated and detailed, including the turn-up at the wall.'],
            ['title' => 'Wet areas', 'text' => 'Bathrooms and balconies are waterproofed before tiling, with the coating carried up the walls so water cannot creep behind the tile.'],
        ],
        'included' => [
            'Inspection of the leak path before any product is chosen',
            'Surface preparation, then coating of every area that was opened',
            'A written note of the terrace, joints, and rooms that were treated',
        ],
        'jobs' => ['Terrace and roof slabs', 'Bathrooms and wet areas', 'Basements and damp walls'],
        'seo_title' => 'Waterproofing in Trivandrum and Kollam | HavenBuild',
        'seo_description' => 'Terrace, bathroom, and wall waterproofing in Trivandrum and Kollam.',
        'seo_keywords' => 'waterproofing Trivandrum, terrace waterproofing Trivandrum, bathroom waterproofing Trivandrum, waterproofing Kollam, damp proofing Kollam',
        'geo_placename' => 'Trivandrum',
        'geo_position' => '8.5241;76.9366',
    ],
    [
        'slug' => 'interior-design',
        'name' => 'Interior design',
        'menu' => 'Interiors',
        'image' => 'images/interior.jpg',
        'alt' => 'A living room in a Kerala concrete house, with a flat ceiling and coconut palms outside',
        'gallery' => [
            ['src' => 'images/interior-kitchen.jpg', 'alt' => 'A kitchen in a Kerala concrete house, with a granite counter and a concrete ceiling'],
            ['src' => 'images/interior-bedroom.jpg', 'alt' => 'A bedroom in a Kerala concrete house looking out to coconut palms'],
            ['src' => 'images/interior-wardrobe.jpg', 'alt' => 'A built-in wardrobe in a Kerala concrete house'],
        ],
        'tint' => 'sage',
        'icon' => 'layout',
        'promise' => 'Layouts, materials, and finishes you can approve before work begins.',
        'coverage' => 'All across Kerala',
        'coverage_note' => 'Interior design is available for homes across Kerala.',
        'summary' => 'We plan how the concrete shell is used: where you sit, what is stored, and how light moves through the day.',
        'story_title' => 'The shell is already there.',
        'story' => [
            'The concrete shell is already there. We plan how it is used: where you sit, where things are stored, and how light moves through the day. Layout, materials, and colours are approved before carpentry starts.',
            'Living rooms, bedrooms, kitchens, and wardrobes are planned together so the materials and storage agree with each other.',
        ],
        'steps' => [
            ['title' => 'How the room is used', 'text' => 'We start with storage, movement, and light. A finish is chosen only after the room has a job.'],
            ['title' => 'Layout', 'text' => 'Furniture, wardrobes, and the kitchen are drawn so doors, windows, and plug points still work once the pieces are in.'],
            ['title' => 'Materials', 'text' => 'Floors, cabinets, stone, and colour are chosen as one set. You see samples before anything is ordered.'],
            ['title' => 'Making it', 'text' => 'Carpentry and finishes follow the signed schedule, room by room, instead of being decided on the day of installation.'],
        ],
        'included' => [
            'A layout based on how each room is used',
            'Material, colour, and storage suggestions you can approve',
            'A finish schedule signed before carpentry begins',
        ],
        'jobs' => ['Living and bedroom layouts', 'Kitchen and wardrobe planning', 'Material and colour selection'],
        'seo_title' => 'Interior Design across Kerala | HavenBuild',
        'seo_description' => 'Home interior design for living rooms, kitchens, and wardrobes across Kerala.',
        'seo_keywords' => 'interior design Kerala, interior designers Kerala, home interiors Kollam, home interiors Trivandrum, kitchen design Kerala',
        'geo_placename' => 'Kerala',
    ],
    [
        'slug' => 'painting',
        'name' => 'Painting',
        'menu' => 'Painting',
        'image' => 'images/painting.jpg',
        'alt' => 'A painter coating a wall inside a Kerala concrete house',
        'gallery' => [
            ['src' => 'images/painting-exterior.jpg', 'alt' => 'The cream wall of a flat-roof Kerala concrete house being painted'],
            ['src' => 'images/painting-prep.jpg', 'alt' => 'Cracks in a concrete wall being filled before painting'],
            ['src' => 'images/painting-ceiling.jpg', 'alt' => 'A painter coating the concrete ceiling of a room'],
        ],
        'tint' => 'sand',
        'icon' => 'brush',
        'promise' => 'Interior and exterior painting with proper prep, not just a fresh coat.',
        'coverage' => 'Kollam and Trivandrum',
        'coverage_note' => 'Painting is available for homes in Kollam and Trivandrum.',
        'summary' => 'Walls are washed, cracks are filled, and a primer goes on before the colour.',
        'story_title' => 'Prepare the wall, then paint it.',
        'story' => [
            'Walls are washed, cracks are filled, and a primer goes on before the colour. Interiors get an even finish. The outside of the house gets a coat that can take sun and rain.',
            'Wood and metal are prepared on their own, so the finish is not just a fresh coat over a tired surface.',
        ],
        'steps' => [
            ['title' => 'Cover and clean', 'text' => 'Floors, fittings, and furniture are protected. Walls are washed and loose paint is scraped back to a sound surface.'],
            ['title' => 'Fill and prime', 'text' => 'Cracks and nail holes are filled. A primer seals the plaster so the finish colour stays even.'],
            ['title' => 'Finish coats', 'text' => 'Colour is applied in even coats, including corners, ceilings, and the edges around doors and windows.'],
            ['title' => 'Outside faces', 'text' => 'Exterior plaster is checked for damp, then given a weather coat that can take sun and rain.'],
        ],
        'included' => [
            'Surface preparation, primer, and finish coats',
            'Floors, fittings, and furniture covered before work starts',
            'Interior walls and ceilings, plus the exterior faces of the house',
        ],
        'jobs' => ['Full interior repaints', 'Exterior weather coats', 'Wood and metal touch-ups'],
        'seo_title' => 'House Painting in Kollam and Trivandrum | HavenBuild',
        'seo_description' => 'Interior and exterior house painting for homes in Kollam and Trivandrum.',
        'seo_keywords' => 'house painting Kollam, painting contractors Kollam, house painting Trivandrum, interior painting Trivandrum, exterior painting Kerala',
        'geo_placename' => 'Kollam, Trivandrum',
    ],
    [
        'slug' => 'solar',
        'name' => 'Solar panel installation',
        'menu' => 'Solar',
        'image' => 'images/solar.jpg',
        'alt' => 'Solar panels on the flat concrete terrace of a Kerala house',
        'gallery' => [
            ['src' => 'images/solar-install.jpg', 'alt' => 'A technician fitting solar cables on a concrete terrace'],
            ['src' => 'images/solar-terrace.jpg', 'alt' => 'A row of solar panels on a flat concrete terrace'],
            ['src' => 'images/solar-inverter.jpg', 'alt' => 'A solar inverter mounted on the wall of a concrete house'],
        ],
        'tint' => 'gold',
        'icon' => 'sun',
        'promise' => 'A rooftop system chosen for the bill, the terrace, and whether the house needs backup.',
        'coverage' => 'All across Kerala',
        'coverage_note' => 'Rooftop solar for homes across Kerala, sized on the terrace before anything is ordered.',
        'summary' => 'The terrace is measured and the shade is checked. The system follows the monthly bill, and whether the house needs power when the grid drops.',
        'story_title' => 'Chosen for the house, not a fixed kit.',
        'story' => [
            'A recent electricity bill and a look at the terrace decide the system. Shade from palms, a water tank, or the next building is marked before a frame goes down. You see whether the house is better on the grid, with a battery, or drawing from the roof alone.',
            'Panels sit on the concrete terrace. Cables run to the inverter and the distribution board. Before we leave, you can read what the system is doing, and you know who to call if the output drops or you want more panels later.',
        ],
        'steps' => [
            ['title' => 'The bill and the roof', 'text' => 'We start from a recent electricity bill and a visit to the terrace. Usable area and shade decide what will actually fit.'],
            ['title' => 'Pick the kind of system', 'text' => 'On-grid when the supply is steady and the aim is a lower bill. Hybrid when chosen circuits should stay on through a cut. Off-grid where the connection is too weak to rely on.'],
            ['title' => 'Mount and connect', 'text' => 'Frames are fixed to the concrete terrace, panels are set, and the inverter is wired to the distribution board.'],
            ['title' => 'Show you the system', 'text' => 'You see the layout, the inverter screen, and what a normal day of generation looks like before we leave.'],
        ],
        'choices' => [
            ['title' => 'On-grid', 'text' => 'Panels supply the house while the sun is up, and spare power goes back to the grid. This suits a home with a steady connection whose main aim is a smaller monthly bill.'],
            ['title' => 'Hybrid', 'text' => 'Panels feed the house and charge a battery. Lights and a few chosen circuits stay on when the grid drops, and the roof still cuts the bill on ordinary days.'],
            ['title' => 'Off-grid', 'text' => 'The house draws from the roof and the battery, without depending on the supply. Used where cuts are long or the connection is weak.'],
        ],
        'aftercare' => [
            ['title' => 'The day we finish', 'text' => 'Mounting, wiring, and a walkthrough of the inverter. You leave knowing how to read what the system is generating.'],
            ['title' => 'A later check', 'text' => 'We come back to look at output, connections, and any shade that has grown in since the panels went up.'],
            ['title' => 'An addition later', 'text' => 'More panels, or a battery on a system that started on-grid, is planned from the same terrace and the same bill.'],
        ],
        'included' => [
            'A visit that measures the terrace and marks the shade',
            'A recommendation of on-grid, hybrid, or off-grid from the bill and the supply',
            'Mounting, wiring to the board, and a walkthrough of the inverter',
            'A later check, and a plan if you want more panels or a battery',
        ],
        'jobs' => ['A new rooftop system for a house', 'A hybrid system with battery backup', 'A small addition to panels already on the terrace'],
        'seo_title' => 'Solar Panel Installation across Kerala | HavenBuild',
        'seo_description' => 'Rooftop solar for homes across Kerala. On-grid, hybrid, and off-grid systems sized from the terrace and the monthly bill.',
        'seo_keywords' => 'solar panel installation Kerala, rooftop solar Kerala, hybrid solar Kerala, on grid solar Kerala, off grid solar Kerala, solar installation Kollam, solar panels Trivandrum',
        'geo_placename' => 'Kerala',
    ],
];
