CREATE DATABASE IF NOT EXISTS havenbuild CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE havenbuild;

CREATE TABLE IF NOT EXISTS enquiries (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  service VARCHAR(80) NOT NULL,
  locality VARCHAR(120) NULL,
  message TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
